In [1]:
import numpy as np

Score = np.random.randint(100, size = (10, 4))
Score

array([[76, 41,  1, 21],
       [31, 63,  8, 75],
       [24, 35, 77, 25],
       [ 9,  7, 69, 20],
       [69, 60, 22, 52],
       [36, 73, 97, 69],
       [34,  0, 17, 97],
       [28, 94, 30, 96],
       [73, 85, 71, 86],
       [56, 30,  8, 80]])

In [2]:
Score_total = np.sum(Score, axis = 0)
print(f'모든 학생의 수학 점수: {Score_total[2]}')

모든 학생의 수학 점수: 400


In [3]:
Score_total_by_students = np.sum(Score, axis = 1)
print(f'각 학생의 과목의 총합 점수: {Score_total_by_students}')

각 학생의 과목의 총합 점수: [139 177 161 105 203 275 148 248 315 174]


In [4]:
odd =  np.arange(Score.shape[0]) % 2 == 0
print(f'홀수번째 학생들 불린 인덱싱으로 접근 : {odd}')

odd_score = np.flip(Score[odd], axis = 1)
print(f'홀수번 학생들의 점수: \n{odd_score}')

홀수번째 학생들 불린 인덱싱으로 접근 : [ True False  True False  True False  True False  True False]
홀수번 학생들의 점수: 
[[21  1 41 76]
 [25 77 35 24]
 [52 22 60 69]
 [97 17  0 34]
 [86 71 85 73]]


In [5]:
Score_max_by_subjects = np.max(Score, axis = 0)
print(f'각 과목에서의 최대 점수: {Score_max_by_subjects}')

각 과목에서의 최대 점수: [76 94 97 97]


In [6]:
Score_eng = Score[:,1]
print(f'영어 과목이 90점 미만인 학생들의 점수: {Score_eng[Score_eng <90]}')

영어 과목이 90점 미만인 학생들의 점수: [41 63 35  7 60 73  0 85 30]


In [7]:
Score_mean_by_subjects = np.mean(Score, axis = 0)
print(f'국어, 영어, 수학, 과학의 평균 점수 {Score_mean_by_subjects}')

국어, 영어, 수학, 과학의 평균 점수 [43.6 48.8 40.  62.1]
