In [2]:
import numpy as np

a = np.random.randint(0, 10, 20)
a = a.reshape(4, 5)

a

array([[4, 6, 7, 9, 6],
       [0, 9, 2, 5, 1],
       [4, 1, 2, 3, 3],
       [7, 8, 9, 5, 6]])

In [3]:
a[a>5] # 이 두가지의 차이 잘 알아두기

array([6, 7, 9, 6, 9, 7, 8, 9, 6])

In [4]:
a>5 # 원소들의 boolean type으로 행렬 반환 -> 앞에 해당 행렬로 묶어주면 해당 조건의 원소들의 행렬로 반환

array([[False,  True,  True,  True,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True, False,  True]])

In [2]:
import numpy as np

a = np.arange(10) # 0부터 9까지 numpy 배열로
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.array()